---
- name: Download, install and reboot all updates
  hosts: all
  tasks:
     - name: Download, install and reboot all updates
       ansible.windows.win_updates:
         category_names: '*'
         reboot: yes
